// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

// @ts-ignore
import { __SPACETIMEDB__, AlgebraicType, ProductType, BuiltinType, ProductTypeElement, DatabaseTable, AlgebraicValue, ReducerArgsAdapter, SumTypeVariant, Serializer, Identity, Address, ReducerEvent, Reducer, SpacetimeDBClient } from "@clockworklabs/spacetimedb-sdk";

export class CompleteTaskReducer extends Reducer
{
	public static reducerName: string = "CompleteTask";
	public static call(_taskId: number) {
		this.getReducer().call(_taskId);
	}

	public call(_taskId: number) {
		const serializer = this.client.getSerializer();
		let _taskIdType = AlgebraicType.createPrimitiveType(BuiltinType.Type.U32);
		serializer.write(_taskIdType, _taskId);
		this.client.call("CompleteTask", serializer);
	}

	public static deserializeArgs(adapter: ReducerArgsAdapter): any[] {
		let taskIdType = AlgebraicType.createPrimitiveType(BuiltinType.Type.U32);
		let taskIdValue = AlgebraicValue.deserialize(taskIdType, adapter.next())
		let taskId = taskIdValue.asNumber();
		return [taskId];
	}

	public static on(callback: (reducerEvent: ReducerEvent, _taskId: number) => void) {
		this.getReducer().on(callback);
	}
	public on(callback: (reducerEvent: ReducerEvent, _taskId: number) => void)
	{
		this.client.on("reducer:CompleteTask", callback);
	}
}


export default CompleteTaskReducer
