// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

// @ts-ignore
import { __SPACETIMEDB__, AlgebraicType, ProductType, BuiltinType, ProductTypeElement, SumType, SumTypeVariant, DatabaseTable, AlgebraicValue, ReducerEvent, Identity, Address, ClientDB, SpacetimeDBClient } from "@clockworklabs/spacetimedb-sdk";

export class Tasks extends DatabaseTable
{
	public static db: ClientDB = __SPACETIMEDB__.clientDB;
	public static tableName = "Tasks";
	public id: number;
	public guestId: number;
	public name: string;
	public completed: boolean;

	public static primaryKey: string | undefined = "id";

	constructor(id: number, guestId: number, name: string, completed: boolean) {
	super();
		this.id = id;
		this.guestId = guestId;
		this.name = name;
		this.completed = completed;
	}

	public static serialize(value: Tasks): object {
		return [
		value.id, value.guestId, value.name, value.completed
		];
	}

	public static getAlgebraicType(): AlgebraicType
	{
		return AlgebraicType.createProductType([
			new ProductTypeElement("id", AlgebraicType.createPrimitiveType(BuiltinType.Type.U32)),
			new ProductTypeElement("guestId", AlgebraicType.createPrimitiveType(BuiltinType.Type.U32)),
			new ProductTypeElement("name", AlgebraicType.createPrimitiveType(BuiltinType.Type.String)),
			new ProductTypeElement("completed", AlgebraicType.createPrimitiveType(BuiltinType.Type.Bool)),
		]);
	}

	public static fromValue(value: AlgebraicValue): Tasks
	{
		let productValue = value.asProductValue();
		let __Id = productValue.elements[0].asNumber();
		let __GuestId = productValue.elements[1].asNumber();
		let __Name = productValue.elements[2].asString();
		let __Completed = productValue.elements[3].asBoolean();
		return new this(__Id, __GuestId, __Name, __Completed);
	}

	public static *filterById(value: number): IterableIterator<Tasks>
	{
		for (let instance of this.db.getTable("Tasks").getInstances())
		{
			if (instance.id === value) {
				yield instance;
			}
		}
	}

	public static findById(value: number): Tasks | undefined
	{
		return this.filterById(value).next().value;
	}

	public static *filterByGuestId(value: number): IterableIterator<Tasks>
	{
		for (let instance of this.db.getTable("Tasks").getInstances())
		{
			if (instance.guestId === value) {
				yield instance;
			}
		}
	}

	public static *filterByName(value: string): IterableIterator<Tasks>
	{
		for (let instance of this.db.getTable("Tasks").getInstances())
		{
			if (instance.name === value) {
				yield instance;
			}
		}
	}

	public static *filterByCompleted(value: boolean): IterableIterator<Tasks>
	{
		for (let instance of this.db.getTable("Tasks").getInstances())
		{
			if (instance.completed === value) {
				yield instance;
			}
		}
	}


}

export default Tasks;
